set shell := ["bash", "-eu", "-o", "pipefail", "-c"]
gymctl := "PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=../src:src python3 -m gymctl"

default:
    @just --list

init:
    @{{gymctl}} init

doctor:
    @{{gymctl}} doctor

build *components:
    @{{gymctl}} build {{components}}

up:
    @{{gymctl}} up

wait:
    @{{gymctl}} wait

info:
    @{{gymctl}} info

status:
    @{{gymctl}} status

reconcile:
    @{{gymctl}} reconcile

prepare-evidence:
    @PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=../src:src python3 -m gym_plugin.dataset --prepare

check:
    @{{gymctl}} check

logs service="":
    @{{gymctl}} logs {{service}}

down:
    @{{gymctl}} down

restart:
    @{{gymctl}} restart

reset CONFIRM="":
    @confirm="{{CONFIRM}}"; {{gymctl}} reset --confirm "${confirm#CONFIRM=}"

clean-restart CONFIRM="":
    @confirm="{{CONFIRM}}"; {{gymctl}} clean-restart --confirm "${confirm#CONFIRM=}"

check-upstreams:
    @{{gymctl}} check-upstreams

update-upstreams:
    @{{gymctl}} update-upstreams
